ingresses:
  - https://kabal-document.intern.dev.nav.no
externalHosts:
  - host: login.microsoftonline.com
  - host: hooks.slack.com
  - host: unleash.nais.io
  - host: pdl-api.dev-fss-pub.nais.io
  - host: dokdistfordeling.dev-fss-pub.nais.io
  - host: dokarkiv-q2.dev-fss-pub.nais.io
  - host: saf-q2.dev-fss-pub.nais.io
springProfile: dev
tenant: trygdeetaten.no
db_tier: db-f1-micro
db_size: 10
db_ha: false
db_type: POSTGRES_15
replicasMin: 2
replicasMax: 2
envs:
  - name: JAVA_OPTS
    value: "-Xms512m -Xmx2048m"
  - name: JAVA_TOOL_OPTIONS
    value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005